batch_size: 7500
max_epochs: 30000
tol: 1.0e-4
lr: 1.0e-3
hidden_v: 512
hidden_ctrl: 512
layers_v: 2
layers_ctrl: 2
dl: 1.0e-3
include_lambda_endpoint: false
seed: 7
deterministic: false
print_interval: 10
prefer_cuda: true
output_dir: outputs
model_prefix: adaptive
